version: '3.4'

services:
  main_web:
    image: mainweb:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_main_web$
    volumes:
      - D:\Documents\4th Year\1st Semester\Open-sourced Apps\Docker\Demo\Main_Web\Main_Web:C:\app
      - C:\Users\nguye\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_main_web$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_main_web$ bin\\Debug\\netcoreapp2.1\\Main_Web.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
